---
title: "Week1"
author: "DataHarmony"
date: '2024-05-02'
output: html_document
---


*Q1 : IMS platformunun belirlenmesi*

SugarCRM, müşteri ilişkileri yönetimi (CRM) yazılımı sunan bir şirkettir. Şirketin tarihçesi ve ürünleri şu şekildedir:

*Kısa Tarihçe:*

SugarCRM, 2004 yılında kurulmuştur.
Şirket, açık kaynaklı bir CRM platformu olarak başladı ve daha sonra ticari bir model benimsedi.
SugarCRM, kullanıcıların müşteri ilişkilerini yönetmelerine, satış faaliyetlerini takip etmelerine, pazarlama kampanyalarını yönetmelerine ve müşteri hizmetlerini iyileştirmelerine olanak tanıyan çeşitli ürünler sunmaktadır.

*Platformun Sunduğu Özellikler:*

Müşteri İlişkileri Yönetimi (CRM)
Satış Yönetimi ve Takibi
Pazarlama Kampanyaları Yönetimi
Müşteri Desteği ve Hizmetleri Yönetimi
Raporlama ve Analiz Araçları
Entegrasyon Yetenekleri (E-posta, Takvim, vs.)
Kişiselleştirme ve Özelleştirme Seçenekleri

*Kullanılan Teknolojiler:*

Yazılım Dili: PHP
Veritabanı: MySQL (Varsayılan olarak)
Web Sunucusu: Apache HTTP Server
Diğer Teknolojiler: JavaScript, HTML, CSS

*API Özellikleri:*

SugarCRM, geliştiricilere RESTful API aracılığıyla platforma erişim sağlar. API'nin sunduğu bazı özellikler şunlardır:
Veri Erişimi ve Manipülasyonu: Kayıt oluşturma, güncelleme, silme.
Modül Yönetimi: Müşteriler, İletişim Kişileri, Satış Fırsatları vb.
Güvenlik ve Yetkilendirme Kontrolleri: Kimlik doğrulama, erişim kontrolleri.
Entegrasyonlar: Üçüncü taraf uygulamalarla entegrasyon sağlama.
Veri Senkronizasyonu: SugarCRM verilerini diğer sistemlerle senkronize etme.
Özelleştirme: API aracılığıyla özel modüller ve iş akışları oluşturma.
SugarCRM, kullanıcı dostu bir arayüzle müşteri ilişkilerini yönetmek için geniş özellikler sunar ve geliştiriciler için API aracılığıyla platformun esnekliğini ve genişletilebilirliğini sağlar.


Seçtiğim kategoriler arasında Customer Relationship Management (CRM) Systems ve IMS platformu olarak SugarCRM'i tercih etmemin temel nedenleri, veri çeşitliliği ve miktarının yanı sıra somut verilerin anlaşılır olmasıyla ilgilidir. Bu platformlar, işletmelerin müşteri ilişkilerini yönetme ihtiyaçlarına çeşitli veri türlerini kapsamlı bir şekilde ele alma yeteneği sunar.

*Q2 : Dataset tanımı*

Veri setlerimizi Kaggle platformunda bulduk ve bu veri setleri banka verilerini içermektedir. Banka verileri, müşteri hesapları, işlem geçmişleri, kredi başvuruları gibi bankacılık faaliyetleriyle ilgili bilgileri içerir. Bu veri setleri, farklı bankaların farklı segmentlerinden veri içerebilir ve genellikle müşteri gizliliğini korumak için anonimleştirilmiş veya toplu olarak sunulmuş verilerdir. Bu banka verilerini birleştirerek IMS platformumuzun işlevselliğini test edebileceğimiz kapsamlı bir veri kümesi oluşturmayı planlıyoruz. Ayrıca, elle oluşturulan telefon numaraları, e-posta adresleri ve isim bilgileri gibi kişisel verileri de ekleyerek platformun farklı veri türlerini işleyişini gözlemleyeceğiz. Düzenleyip elde edilen son veri “csv” formatında olacaktır. Kullanacağımız verinin boyutu henüz kesin olmamakla birlikte ortalama 20 MB civarında olacağı öngörülmektedir. Verilerimizi IMS’e ithal etmek için tarayıcı üzerinden SugarCRM hesabımıza giriş yaptıktan sonra SugarCRM'in ana menüsünden "Import"  seçeneğini seçiyoruz. Daha sonra CSV dosyamızda ki sütunları SugarCRM'deki alanlarla eşleştiriyoruz. Verileri doğru eşleştirdiğimize emin olduktan sonra veri ithalatını gerçekleştirmek için “Import now” butonuna tıklıyoruz. IMS platformumuzdaki verileri R programlama diliyle çekmek için SugarCRM'in REST API'sini kullanmayı planlıyoruz. Bu API, SugarCRM'in sağladığı verilere programatik olarak erişmemize ve bu verileri IMS platformumuza entegre etmemize olanak tanır. REST API, HTTP protokolünü kullanarak belirli bir URL yapısına gönderilen isteklerle çalışır. Bu istekler, belirli veri kaynaklarına erişmek veya belirli işlemleri gerçekleştirmek için kullanılır. SugarCRM'in REST API'si de bu şekilde çalışır ve bize SugarCRM platformundaki verilere erişim imkanı sunar. API aracılığıyla IMS platformumuzun SugarCRM'den veri çekme işlemi, öncelikle yetkilendirme ve kimlik doğrulama süreçlerini içerecek şekilde yapılandırılacaktır. Daha sonra, belirli veri kaynaklarından istenilen verileri çekmek için API istekleri oluşturulacak ve bu veriler IMS platformumuzda kullanılmak üzere işlenecektir. Bu strateji, IMS platformumuzun güncel verilere erişimini sağlayarak analiz ve raporlama süreçlerimizi optimize etmemize yardımcı olacaktır.

*Kaggle veri setleri:* 

https://www.kaggle.com/datasets/thedevastator/predicting-credit-card-customer-attrition-with-m
https://www.kaggle.com/datasets/shivamb/bank-customer-segmentation
https://www.kaggle.com/datasets/zain280/bank-customer-information-and-marketing-response

*Q3 : İş  tanımı*

Şirketimiz DataHarmony, SugarCRM'i kullanan bir şirket olarak, müşteri ilişkileri yönetimi (CRM) ve veri entegrasyonu alanında uzmanlaşmış bir işletmedir. IMS (İş İletişim Yönetimi) çözümlerini kullanarak müşterilerin işletme süreçlerini optimize etmeyi ve verimliliği artırmayı hedefler.


DataHarmony, SugarCRM'i kullanan bir şirket olarak, müşteri ilişkileri yönetimi (CRM) ve veri entegrasyonu alanında uzmanlaşmış bir işletmedir. IMS (İş İletişim Yönetimi) çözümlerini kullanarak müşterilerin işletme süreçlerini optimize etmeyi ve verimliliği artırmayı hedefler.

*Tanımı:* DataHarmony, müşterilerin işletme süreçlerini iyileştirmek için SugarCRM ve IMS çözümlerini entegre eden bir teknoloji şirketidir.
Aktiviteleri ve Rutin Operasyonları:
Müşteri ihtiyaçlarını analiz etme ve gereksinimlerini belirleme.
SugarCRM ve IMS entegrasyonunu gerçekleştirme ve özelleştirme.
Müşteri eğitimi ve destek sağlama.
Müşteri geri bildirimlerini toplama ve ürün iyileştirmeleri için geri bildirimleri değerlendirme.
Yeni pazarlama stratejileri geliştirme ve uygulama.
Gelir Modeli: DataHarmony, SugarCRM ve IMS entegrasyon hizmetleri sunarak ve danışmanlık ve özelleştirme hizmetleri üzerinden gelir elde eder.  Şirketimizin mevcut gelir kaynağı ise Shock Bank’ a verdiğimiz danışmanlık hizmetleri üzerinden sağlanmaktadır.

Olası rakipler genellikle büyük CRM sağlayıcıları, bulut tabanlı yazılım şirketleri ve müşteri ilişkileri yönetimi çözümleri sunan firmalar olacaktır. Bu rakipler genellikle geniş bir müşteri tabanına ve kapsamlı bir ürün yelpazesine sahiptir. Büyük CRM sağlayıcıları dünya çapında tanınmış, bulut tabanlı yazılım şirketleri esnek fiyatlandırma modelleri ve özellik zenginliği sunar. Müşteri ilişkileri yönetimi çözümleri sağlayıcıları ise belirli sektörlere odaklanmış çözümler sunarak rekabet avantajı sağlarlar.

